// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"clock-in/app/worktime/service/internal/data/ent/migrate"

	"clock-in/app/worktime/service/internal/data/ent/worktime"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Worktime is the client for interacting with the Worktime builders.
	Worktime *WorktimeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Worktime = NewWorktimeClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Worktime: NewWorktimeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:   cfg,
		Worktime: NewWorktimeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Worktime.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Worktime.Use(hooks...)
}

// WorktimeClient is a client for the Worktime schema.
type WorktimeClient struct {
	config
}

// NewWorktimeClient returns a client for the Worktime from the given config.
func NewWorktimeClient(c config) *WorktimeClient {
	return &WorktimeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `worktime.Hooks(f(g(h())))`.
func (c *WorktimeClient) Use(hooks ...Hook) {
	c.hooks.Worktime = append(c.hooks.Worktime, hooks...)
}

// Create returns a create builder for Worktime.
func (c *WorktimeClient) Create() *WorktimeCreate {
	mutation := newWorktimeMutation(c.config, OpCreate)
	return &WorktimeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Worktime entities.
func (c *WorktimeClient) CreateBulk(builders ...*WorktimeCreate) *WorktimeCreateBulk {
	return &WorktimeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Worktime.
func (c *WorktimeClient) Update() *WorktimeUpdate {
	mutation := newWorktimeMutation(c.config, OpUpdate)
	return &WorktimeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorktimeClient) UpdateOne(w *Worktime) *WorktimeUpdateOne {
	mutation := newWorktimeMutation(c.config, OpUpdateOne, withWorktime(w))
	return &WorktimeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorktimeClient) UpdateOneID(id int) *WorktimeUpdateOne {
	mutation := newWorktimeMutation(c.config, OpUpdateOne, withWorktimeID(id))
	return &WorktimeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Worktime.
func (c *WorktimeClient) Delete() *WorktimeDelete {
	mutation := newWorktimeMutation(c.config, OpDelete)
	return &WorktimeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *WorktimeClient) DeleteOne(w *Worktime) *WorktimeDeleteOne {
	return c.DeleteOneID(w.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *WorktimeClient) DeleteOneID(id int) *WorktimeDeleteOne {
	builder := c.Delete().Where(worktime.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorktimeDeleteOne{builder}
}

// Query returns a query builder for Worktime.
func (c *WorktimeClient) Query() *WorktimeQuery {
	return &WorktimeQuery{
		config: c.config,
	}
}

// Get returns a Worktime entity by its id.
func (c *WorktimeClient) Get(ctx context.Context, id int) (*Worktime, error) {
	return c.Query().Where(worktime.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorktimeClient) GetX(ctx context.Context, id int) *Worktime {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorktimeClient) Hooks() []Hook {
	return c.hooks.Worktime
}
