// Code generated by entc, DO NOT EDIT.

package ent

import (
	"clock-in/app/worktime/service/internal/data/ent/predicate"
	"clock-in/app/worktime/service/internal/data/ent/worktime"
	"context"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeWorktime = "Worktime"
)

// WorktimeMutation represents an operation that mutates the Worktime nodes in the graph.
type WorktimeMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user          *int64
	adduser       *int64
	day           *int64
	addday        *int64
	minute        *int64
	addminute     *int64
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Worktime, error)
	predicates    []predicate.Worktime
}

var _ ent.Mutation = (*WorktimeMutation)(nil)

// worktimeOption allows management of the mutation configuration using functional options.
type worktimeOption func(*WorktimeMutation)

// newWorktimeMutation creates new mutation for the Worktime entity.
func newWorktimeMutation(c config, op Op, opts ...worktimeOption) *WorktimeMutation {
	m := &WorktimeMutation{
		config:        c,
		op:            op,
		typ:           TypeWorktime,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWorktimeID sets the ID field of the mutation.
func withWorktimeID(id int) worktimeOption {
	return func(m *WorktimeMutation) {
		var (
			err   error
			once  sync.Once
			value *Worktime
		)
		m.oldValue = func(ctx context.Context) (*Worktime, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Worktime.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWorktime sets the old Worktime of the mutation.
func withWorktime(node *Worktime) worktimeOption {
	return func(m *WorktimeMutation) {
		m.oldValue = func(context.Context) (*Worktime, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WorktimeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WorktimeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WorktimeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetUser sets the "user" field.
func (m *WorktimeMutation) SetUser(i int64) {
	m.user = &i
	m.adduser = nil
}

// User returns the value of the "user" field in the mutation.
func (m *WorktimeMutation) User() (r int64, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUser returns the old "user" field's value of the Worktime entity.
// If the Worktime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WorktimeMutation) OldUser(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUser: %w", err)
	}
	return oldValue.User, nil
}

// AddUser adds i to the "user" field.
func (m *WorktimeMutation) AddUser(i int64) {
	if m.adduser != nil {
		*m.adduser += i
	} else {
		m.adduser = &i
	}
}

// AddedUser returns the value that was added to the "user" field in this mutation.
func (m *WorktimeMutation) AddedUser() (r int64, exists bool) {
	v := m.adduser
	if v == nil {
		return
	}
	return *v, true
}

// ResetUser resets all changes to the "user" field.
func (m *WorktimeMutation) ResetUser() {
	m.user = nil
	m.adduser = nil
}

// SetDay sets the "day" field.
func (m *WorktimeMutation) SetDay(i int64) {
	m.day = &i
	m.addday = nil
}

// Day returns the value of the "day" field in the mutation.
func (m *WorktimeMutation) Day() (r int64, exists bool) {
	v := m.day
	if v == nil {
		return
	}
	return *v, true
}

// OldDay returns the old "day" field's value of the Worktime entity.
// If the Worktime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WorktimeMutation) OldDay(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDay is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDay requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDay: %w", err)
	}
	return oldValue.Day, nil
}

// AddDay adds i to the "day" field.
func (m *WorktimeMutation) AddDay(i int64) {
	if m.addday != nil {
		*m.addday += i
	} else {
		m.addday = &i
	}
}

// AddedDay returns the value that was added to the "day" field in this mutation.
func (m *WorktimeMutation) AddedDay() (r int64, exists bool) {
	v := m.addday
	if v == nil {
		return
	}
	return *v, true
}

// ResetDay resets all changes to the "day" field.
func (m *WorktimeMutation) ResetDay() {
	m.day = nil
	m.addday = nil
}

// SetMinute sets the "minute" field.
func (m *WorktimeMutation) SetMinute(i int64) {
	m.minute = &i
	m.addminute = nil
}

// Minute returns the value of the "minute" field in the mutation.
func (m *WorktimeMutation) Minute() (r int64, exists bool) {
	v := m.minute
	if v == nil {
		return
	}
	return *v, true
}

// OldMinute returns the old "minute" field's value of the Worktime entity.
// If the Worktime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WorktimeMutation) OldMinute(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldMinute is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldMinute requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinute: %w", err)
	}
	return oldValue.Minute, nil
}

// AddMinute adds i to the "minute" field.
func (m *WorktimeMutation) AddMinute(i int64) {
	if m.addminute != nil {
		*m.addminute += i
	} else {
		m.addminute = &i
	}
}

// AddedMinute returns the value that was added to the "minute" field in this mutation.
func (m *WorktimeMutation) AddedMinute() (r int64, exists bool) {
	v := m.addminute
	if v == nil {
		return
	}
	return *v, true
}

// ResetMinute resets all changes to the "minute" field.
func (m *WorktimeMutation) ResetMinute() {
	m.minute = nil
	m.addminute = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *WorktimeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *WorktimeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Worktime entity.
// If the Worktime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WorktimeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *WorktimeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *WorktimeMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *WorktimeMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Worktime entity.
// If the Worktime object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WorktimeMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *WorktimeMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the WorktimeMutation builder.
func (m *WorktimeMutation) Where(ps ...predicate.Worktime) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *WorktimeMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Worktime).
func (m *WorktimeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WorktimeMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.user != nil {
		fields = append(fields, worktime.FieldUser)
	}
	if m.day != nil {
		fields = append(fields, worktime.FieldDay)
	}
	if m.minute != nil {
		fields = append(fields, worktime.FieldMinute)
	}
	if m.created_at != nil {
		fields = append(fields, worktime.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, worktime.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WorktimeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case worktime.FieldUser:
		return m.User()
	case worktime.FieldDay:
		return m.Day()
	case worktime.FieldMinute:
		return m.Minute()
	case worktime.FieldCreatedAt:
		return m.CreatedAt()
	case worktime.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WorktimeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case worktime.FieldUser:
		return m.OldUser(ctx)
	case worktime.FieldDay:
		return m.OldDay(ctx)
	case worktime.FieldMinute:
		return m.OldMinute(ctx)
	case worktime.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case worktime.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Worktime field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WorktimeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case worktime.FieldUser:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUser(v)
		return nil
	case worktime.FieldDay:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDay(v)
		return nil
	case worktime.FieldMinute:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinute(v)
		return nil
	case worktime.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case worktime.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Worktime field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WorktimeMutation) AddedFields() []string {
	var fields []string
	if m.adduser != nil {
		fields = append(fields, worktime.FieldUser)
	}
	if m.addday != nil {
		fields = append(fields, worktime.FieldDay)
	}
	if m.addminute != nil {
		fields = append(fields, worktime.FieldMinute)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WorktimeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case worktime.FieldUser:
		return m.AddedUser()
	case worktime.FieldDay:
		return m.AddedDay()
	case worktime.FieldMinute:
		return m.AddedMinute()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WorktimeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case worktime.FieldUser:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUser(v)
		return nil
	case worktime.FieldDay:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDay(v)
		return nil
	case worktime.FieldMinute:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinute(v)
		return nil
	}
	return fmt.Errorf("unknown Worktime numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WorktimeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WorktimeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WorktimeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Worktime nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WorktimeMutation) ResetField(name string) error {
	switch name {
	case worktime.FieldUser:
		m.ResetUser()
		return nil
	case worktime.FieldDay:
		m.ResetDay()
		return nil
	case worktime.FieldMinute:
		m.ResetMinute()
		return nil
	case worktime.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case worktime.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Worktime field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WorktimeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WorktimeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WorktimeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WorktimeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WorktimeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WorktimeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WorktimeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Worktime unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WorktimeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Worktime edge %s", name)
}
