// Code generated by entc, DO NOT EDIT.

package ent

import (
	"clock-in/app/worktime/service/internal/data/ent/schema"
	"clock-in/app/worktime/service/internal/data/ent/worktime"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	worktimeFields := schema.Worktime{}.Fields()
	_ = worktimeFields
	// worktimeDescUpdatedAt is the schema descriptor for updated_at field.
	worktimeDescUpdatedAt := worktimeFields[4].Descriptor()
	// worktime.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	worktime.DefaultUpdatedAt = worktimeDescUpdatedAt.Default.(func() time.Time)
}
