// Code generated by entc, DO NOT EDIT.

package ent

import (
	"clock-in/app/worktime/service/internal/data/ent/predicate"
	"clock-in/app/worktime/service/internal/data/ent/worktime"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorktimeUpdate is the builder for updating Worktime entities.
type WorktimeUpdate struct {
	config
	hooks    []Hook
	mutation *WorktimeMutation
}

// Where appends a list predicates to the WorktimeUpdate builder.
func (wu *WorktimeUpdate) Where(ps ...predicate.Worktime) *WorktimeUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUser sets the "user" field.
func (wu *WorktimeUpdate) SetUser(i int64) *WorktimeUpdate {
	wu.mutation.ResetUser()
	wu.mutation.SetUser(i)
	return wu
}

// AddUser adds i to the "user" field.
func (wu *WorktimeUpdate) AddUser(i int64) *WorktimeUpdate {
	wu.mutation.AddUser(i)
	return wu
}

// SetDay sets the "day" field.
func (wu *WorktimeUpdate) SetDay(i int64) *WorktimeUpdate {
	wu.mutation.ResetDay()
	wu.mutation.SetDay(i)
	return wu
}

// AddDay adds i to the "day" field.
func (wu *WorktimeUpdate) AddDay(i int64) *WorktimeUpdate {
	wu.mutation.AddDay(i)
	return wu
}

// SetMinute sets the "minute" field.
func (wu *WorktimeUpdate) SetMinute(i int64) *WorktimeUpdate {
	wu.mutation.ResetMinute()
	wu.mutation.SetMinute(i)
	return wu
}

// AddMinute adds i to the "minute" field.
func (wu *WorktimeUpdate) AddMinute(i int64) *WorktimeUpdate {
	wu.mutation.AddMinute(i)
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WorktimeUpdate) SetCreatedAt(t time.Time) *WorktimeUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WorktimeUpdate) SetUpdatedAt(t time.Time) *WorktimeUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wu *WorktimeUpdate) SetNillableUpdatedAt(t *time.Time) *WorktimeUpdate {
	if t != nil {
		wu.SetUpdatedAt(*t)
	}
	return wu
}

// Mutation returns the WorktimeMutation object of the builder.
func (wu *WorktimeUpdate) Mutation() *WorktimeMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorktimeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wu.hooks) == 0 {
		affected, err = wu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorktimeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wu.mutation = mutation
			affected, err = wu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wu.hooks) - 1; i >= 0; i-- {
			if wu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorktimeUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorktimeUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorktimeUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WorktimeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   worktime.Table,
			Columns: worktime.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: worktime.FieldID,
			},
		},
	}
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldUser,
		})
	}
	if value, ok := wu.mutation.AddedUser(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldUser,
		})
	}
	if value, ok := wu.mutation.Day(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldDay,
		})
	}
	if value, ok := wu.mutation.AddedDay(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldDay,
		})
	}
	if value, ok := wu.mutation.Minute(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldMinute,
		})
	}
	if value, ok := wu.mutation.AddedMinute(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldMinute,
		})
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: worktime.FieldCreatedAt,
		})
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: worktime.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worktime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// WorktimeUpdateOne is the builder for updating a single Worktime entity.
type WorktimeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorktimeMutation
}

// SetUser sets the "user" field.
func (wuo *WorktimeUpdateOne) SetUser(i int64) *WorktimeUpdateOne {
	wuo.mutation.ResetUser()
	wuo.mutation.SetUser(i)
	return wuo
}

// AddUser adds i to the "user" field.
func (wuo *WorktimeUpdateOne) AddUser(i int64) *WorktimeUpdateOne {
	wuo.mutation.AddUser(i)
	return wuo
}

// SetDay sets the "day" field.
func (wuo *WorktimeUpdateOne) SetDay(i int64) *WorktimeUpdateOne {
	wuo.mutation.ResetDay()
	wuo.mutation.SetDay(i)
	return wuo
}

// AddDay adds i to the "day" field.
func (wuo *WorktimeUpdateOne) AddDay(i int64) *WorktimeUpdateOne {
	wuo.mutation.AddDay(i)
	return wuo
}

// SetMinute sets the "minute" field.
func (wuo *WorktimeUpdateOne) SetMinute(i int64) *WorktimeUpdateOne {
	wuo.mutation.ResetMinute()
	wuo.mutation.SetMinute(i)
	return wuo
}

// AddMinute adds i to the "minute" field.
func (wuo *WorktimeUpdateOne) AddMinute(i int64) *WorktimeUpdateOne {
	wuo.mutation.AddMinute(i)
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WorktimeUpdateOne) SetCreatedAt(t time.Time) *WorktimeUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WorktimeUpdateOne) SetUpdatedAt(t time.Time) *WorktimeUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wuo *WorktimeUpdateOne) SetNillableUpdatedAt(t *time.Time) *WorktimeUpdateOne {
	if t != nil {
		wuo.SetUpdatedAt(*t)
	}
	return wuo
}

// Mutation returns the WorktimeMutation object of the builder.
func (wuo *WorktimeUpdateOne) Mutation() *WorktimeMutation {
	return wuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorktimeUpdateOne) Select(field string, fields ...string) *WorktimeUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Worktime entity.
func (wuo *WorktimeUpdateOne) Save(ctx context.Context) (*Worktime, error) {
	var (
		err  error
		node *Worktime
	)
	if len(wuo.hooks) == 0 {
		node, err = wuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorktimeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wuo.mutation = mutation
			node, err = wuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wuo.hooks) - 1; i >= 0; i-- {
			if wuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorktimeUpdateOne) SaveX(ctx context.Context) *Worktime {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorktimeUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorktimeUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WorktimeUpdateOne) sqlSave(ctx context.Context) (_node *Worktime, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   worktime.Table,
			Columns: worktime.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: worktime.FieldID,
			},
		},
	}
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Worktime.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worktime.FieldID)
		for _, f := range fields {
			if !worktime.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worktime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldUser,
		})
	}
	if value, ok := wuo.mutation.AddedUser(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldUser,
		})
	}
	if value, ok := wuo.mutation.Day(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldDay,
		})
	}
	if value, ok := wuo.mutation.AddedDay(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldDay,
		})
	}
	if value, ok := wuo.mutation.Minute(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldMinute,
		})
	}
	if value, ok := wuo.mutation.AddedMinute(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: worktime.FieldMinute,
		})
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: worktime.FieldCreatedAt,
		})
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: worktime.FieldUpdatedAt,
		})
	}
	_node = &Worktime{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worktime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
