// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"clock-in/app/clockin/interface/internal/biz"
	"clock-in/app/clockin/interface/internal/conf"
	"clock-in/app/clockin/interface/internal/data"
	"clock-in/app/clockin/interface/internal/server"
	"clock-in/app/clockin/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userServiceClient := data.NewUserClient(confData)
	recordServiceClient := data.NewRecordClient(confData)
	dataData, err := data.NewData(confData, logger, userServiceClient, recordServiceClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(userRepo, logger)
	recordRepo := data.NewRecordRepo(dataData, logger)
	clockInUsecase := biz.NewClockInUsecase(recordRepo, logger)
	clockInService := service.NewClockInService(authUsecase, clockInUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, clockInService, logger)
	httpServer := server.NewHTTPServer(confServer, clockInService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
