// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: api/statistics/service/v1/statistics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Day    int64 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Minute int64 `protobuf:"varint,3,opt,name=minute,proto3" json:"minute,omitempty"`
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *Statistics) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Statistics) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Statistics) GetMinute() int64 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    int64 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	User   int64 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Moment int64 `protobuf:"varint,3,opt,name=moment,proto3" json:"moment,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Record) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Record) GetMoment() int64 {
	if x != nil {
		return x.Moment
	}
	return 0
}

type GetUserStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64   `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Day  []int64 `protobuf:"varint,2,rep,packed,name=day,proto3" json:"day,omitempty"`
}

func (x *GetUserStatisticsRequest) Reset() {
	*x = GetUserStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatisticsRequest) ProtoMessage() {}

func (x *GetUserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserStatisticsRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *GetUserStatisticsRequest) GetDay() []int64 {
	if x != nil {
		return x.Day
	}
	return nil
}

type GetUserStatisticsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statistics []*Statistics `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
}

func (x *GetUserStatisticsReply) Reset() {
	*x = GetUserStatisticsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatisticsReply) ProtoMessage() {}

func (x *GetUserStatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatisticsReply.ProtoReflect.Descriptor instead.
func (*GetUserStatisticsReply) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatisticsReply) GetStatistics() []*Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type CreateStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   int64     `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Record []*Record `protobuf:"bytes,2,rep,name=record,proto3" json:"record,omitempty"`
}

func (x *CreateStatisticsRequest) Reset() {
	*x = CreateStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatisticsRequest) ProtoMessage() {}

func (x *CreateStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatisticsRequest.ProtoReflect.Descriptor instead.
func (*CreateStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStatisticsRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CreateStatisticsRequest) GetRecord() []*Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateStatisticsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateStatisticsReply) Reset() {
	*x = CreateStatisticsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatisticsReply) ProtoMessage() {}

func (x *CreateStatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_statistics_service_v1_statistics_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatisticsReply.ProtoReflect.Descriptor instead.
func (*CreateStatisticsReply) Descriptor() ([]byte, []int) {
	return file_api_statistics_service_v1_statistics_proto_rawDescGZIP(), []int{5}
}

var File_api_statistics_service_v1_statistics_proto protoreflect.FileDescriptor

var file_api_statistics_service_v1_statistics_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x46, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22,
	0x46, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x5f, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x68, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x8a, 0x02,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x78, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x12, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x44, 0x0a, 0x19, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x25, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x2d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_statistics_service_v1_statistics_proto_rawDescOnce sync.Once
	file_api_statistics_service_v1_statistics_proto_rawDescData = file_api_statistics_service_v1_statistics_proto_rawDesc
)

func file_api_statistics_service_v1_statistics_proto_rawDescGZIP() []byte {
	file_api_statistics_service_v1_statistics_proto_rawDescOnce.Do(func() {
		file_api_statistics_service_v1_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_statistics_service_v1_statistics_proto_rawDescData)
	})
	return file_api_statistics_service_v1_statistics_proto_rawDescData
}

var file_api_statistics_service_v1_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_statistics_service_v1_statistics_proto_goTypes = []interface{}{
	(*Statistics)(nil),               // 0: api.statistics.service.v1.Statistics
	(*Record)(nil),                   // 1: api.statistics.service.v1.Record
	(*GetUserStatisticsRequest)(nil), // 2: api.statistics.service.v1.GetUserStatisticsRequest
	(*GetUserStatisticsReply)(nil),   // 3: api.statistics.service.v1.GetUserStatisticsReply
	(*CreateStatisticsRequest)(nil),  // 4: api.statistics.service.v1.CreateStatisticsRequest
	(*CreateStatisticsReply)(nil),    // 5: api.statistics.service.v1.CreateStatisticsReply
}
var file_api_statistics_service_v1_statistics_proto_depIdxs = []int32{
	0, // 0: api.statistics.service.v1.GetUserStatisticsReply.statistics:type_name -> api.statistics.service.v1.Statistics
	1, // 1: api.statistics.service.v1.CreateStatisticsRequest.record:type_name -> api.statistics.service.v1.Record
	2, // 2: api.statistics.service.v1.StatisticsService.GetUserStatistics:input_type -> api.statistics.service.v1.GetUserStatisticsRequest
	4, // 3: api.statistics.service.v1.StatisticsService.CreateStatistics:input_type -> api.statistics.service.v1.CreateStatisticsRequest
	3, // 4: api.statistics.service.v1.StatisticsService.GetUserStatistics:output_type -> api.statistics.service.v1.GetUserStatisticsReply
	5, // 5: api.statistics.service.v1.StatisticsService.CreateStatistics:output_type -> api.statistics.service.v1.CreateStatisticsReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_statistics_service_v1_statistics_proto_init() }
func file_api_statistics_service_v1_statistics_proto_init() {
	if File_api_statistics_service_v1_statistics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_statistics_service_v1_statistics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statistics_service_v1_statistics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statistics_service_v1_statistics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statistics_service_v1_statistics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStatisticsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statistics_service_v1_statistics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statistics_service_v1_statistics_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStatisticsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_statistics_service_v1_statistics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_statistics_service_v1_statistics_proto_goTypes,
		DependencyIndexes: file_api_statistics_service_v1_statistics_proto_depIdxs,
		MessageInfos:      file_api_statistics_service_v1_statistics_proto_msgTypes,
	}.Build()
	File_api_statistics_service_v1_statistics_proto = out.File
	file_api_statistics_service_v1_statistics_proto_rawDesc = nil
	file_api_statistics_service_v1_statistics_proto_goTypes = nil
	file_api_statistics_service_v1_statistics_proto_depIdxs = nil
}
